name: Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  BUILD_TYPE: Release
  METIS_LIB_DIR: /usr/lib/x86_64-linux-gnu
  METIS_INC_DIR: /usr/include
  RABBIT_ORDER_INC_DIR: /usr/include

jobs:

  test_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: MSYS2 Setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-python mingw-w64-x86_64-ninja

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DRUN_TESTS=ON

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j 2

      - name: Run Examples
        working-directory: ${{github.workspace}}/build/examples
        run: python3 run_all_examples.py

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V

  test_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: brew install llvm libomp python3 cmake make

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRUN_TESTS=ON -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

      - name: Run Examples
        working-directory: ${{github.workspace}}/build/examples
        run: python3 run_all_examples.py

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V

  test_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y cmake make gcc libomp-dev python3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRUN_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

      - name: Run Examples
        working-directory: ${{github.workspace}}/build/examples
        run: python3 run_all_examples.py

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: sudo cmake --install .

      - name: Test Install
        working-directory: ${{github.workspace}}/examples
        run: |
          g++ csr_coo/csr_coo.cc -lsparsebase -fopenmp -O3 -std=c++17
          g++ degree_order/degree_order.cc -lsparsebase -fopenmp -O3 -std=c++17



  test_header_only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y cmake make gcc libomp-dev python3

      - name: Configure CMake (Header Only)
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D_HEADER_ONLY=ON -DRUN_TESTS=ON

      - name: Build (Header Only)
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

      - name: Run Examples (Header Only)
        working-directory: ${{github.workspace}}/build/examples
        run: python3 run_all_examples.py

      - name: Run Tests (Header Only)
        working-directory: ${{github.workspace}}/build
        run: ctest -V

      - name: Install (Header Only)
        working-directory: ${{github.workspace}}/build
        run: sudo cmake --install .

      - name: Test Install (Header Only)
        working-directory: ${{github.workspace}}/examples
        run: |
          g++ csr_coo/csr_coo.cc -lsparsebase -fopenmp -O3 -std=c++17
          g++ degree_order/degree_order.cc -lsparsebase -fopenmp -O3 -std=c++17


  test_opt_dep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y cmake make gcc libomp-dev python3 libmetis-dev libboost-all-dev

      - name: Install Non-System Dependencies
        run: sudo wget https://raw.githubusercontent.com/araij/rabbit_order/master/rabbit_order.hpp -O /usr/include/rabbit_order.hpp

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRUN_TESTS=ON -DUSE_METIS=ON -DUSE_RABBIT_ORDER=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

      - name: Run Examples
        working-directory: ${{github.workspace}}/build/examples
        run: python3 run_all_examples.py

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V
